apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn:  arn:aws:iam::042418029664:user/sampath 
      username: sampath
      groups:
        - system:masters
