# Service - LoadBalancer
#lb.yaml
apiVersion: v1
kind: Service	
metadata:
  name: my-service
  labels:
    app: nginx-app-1
spec:
  selector:
    app: nginx-app-1
  type: LoadBalancer
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80
